CREATE TABLE `bioinfo`.`animals` (
                                     `idanimals` INT NOT NULL AUTO_INCREMENT,
                                     `kingdom` VARCHAR(120) NOT NULL,
                                     `phylum` VARCHAR(120) NOT NULL,
                                     `class` VARCHAR(120) NOT NULL,
                                     `subclass` VARCHAR(120) NOT NULL,
                                     `order` VARCHAR(120) NOT NULL,
                                     `family` VARCHAR(120) NOT NULL,
                                     `subfamily` VARCHAR(120) NOT NULL,
                                     `genus` VARCHAR(120) NOT NULL,
                                     `subgenus` VARCHAR(120) NOT NULL,
                                     `epiteto` VARCHAR(120) NOT NULL,
                                     `species` VARCHAR(120) NOT NULL,
                                     `subspecies` VARCHAR(120) NOT NULL,
                                     `functional_group` VARCHAR(120) NOT NULL,
                                     `abundance` VARCHAR(120) NOT NULL,
                                     `sexo` VARCHAR(120) NOT NULL,
                                     `caste` VARCHAR(120) NOT NULL,
                                     `development_stage` VARCHAR(120) NOT NULL,
                                     `determination_start` VARCHAR(120) NOT NULL,
                                     `determination_end` VARCHAR(120) NOT NULL,
                                     `biomass` VARCHAR(120) NOT NULL,
                                     PRIMARY KEY (`idanimals`));